#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rkhilenk <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/09/10 14:09:54 by rkhilenk          #+#    #+#              #
#    Updated: 2017/09/10 14:09:54 by rkhilenk         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

SRC = rush_2.c ft_putchar.c check00.c check01.c check02.c check03.c check04.c check_r.c check_sq.c

all: Ragnarock

Ragnarock:
	@gcc $(SRC) -Wall -Wextra -Werror -o rush-2

clean:
	@rm -f rush-2

fclean:clean

re:all fclean